TICK_SIZE = 256

WHOLE_NOTE_LENGTH = int(TICK_SIZE * 4)
HALF_NOTE_LENGTH = int(TICK_SIZE * 2)
QUARTER_NOTE_LENGTH = int(TICK_SIZE)
EIGHTH_NOTE_LENGTH = int(TICK_SIZE / 2)
SIXTEENTH_NOTE_LENGTH = int(TICK_SIZE / 4)

